export const getImagePath = (imageNameWithExtension: string): string => {
  // eslint-disable-next-line import/no-dynamic-require
  return require(`./${imageNameWithExtension}`);
};
export const topBanner = getImagePath("top-banner-bg.png");
export const logo = getImagePath("logo.svg");
export const mobileLogo = getImagePath("mobile-logo.svg");
export const menuIcon = getImagePath("menu-icon.svg");
export const meetingBanner = getImagePath("meeting-banner.png");
export const lockIconBlue = getImagePath("lock-icon-blue.svg");
export const clockIconBlue = getImagePath("clock-icon-blue.svg");
export const increasingIconBlue = getImagePath("increasing-blue-icon.svg");
export const happyFaceIconBlue = getImagePath("happy-face-blue-icon.svg");
export const awardIconBlue = getImagePath("award-blue-icon.svg");
export const goalIconBlue = getImagePath("goal-blue-icon.svg");
export const meetingImg = getImagePath("meeting-img.png");
export const slideImg1 = getImagePath("slide-img-1.jpg");
export const slideImg2 = getImagePath("slide-img-2.jpg");
export const slideImg3 = getImagePath("slide-img-3.jpg");
export const arrowLeftIcon = getImagePath("arrow-left-icon.svg");
export const arrowRightIcon = getImagePath("arrow-right-icon.svg");
export const codiconLockIconBlue = getImagePath("codicon_lock-blue-icon.svg");
export const cursorClickIconBlue = getImagePath("cursor-click-blue-icon.svg");
export const settingsIconBlue = getImagePath("settings-blue-icon.svg");
export const fastForwardIconBlue = getImagePath("fast-forward-blue-icon.svg");
export const chartIconBlue = getImagePath("chart-blue-icon.svg");
export const macBookAir = getImagePath("macbook-air.png");
export const rightIndicatorIcon = getImagePath("right-indicator-icon.svg");
export const brandLogo1 = getImagePath("brand-logo-1.png");
export const brandLogo2 = getImagePath("brand-logo-2.png");
export const brandLogo3 = getImagePath("brand-logo-3.png");
export const brandLogo4 = getImagePath("brand-logo-4.png");
export const brandLogo5 = getImagePath("brand-logo-5.png");
export const brandLogo6 = getImagePath("brand-logo-6.png");
export const faceBookIcon = getImagePath("facebook-icon.svg");
export const twitterIcon = getImagePath("twitter-icon.svg");
export const instagramIcon = getImagePath("instagram-icon.svg");
export const envelopIcon = getImagePath("envelop-icon.svg");
export const callIcon = getImagePath("call-icon.svg");
export const locationIcon = getImagePath("location-icon.svg");
